<a href="https://colab.research.google.com/github/jeungsengho/python8month/blob/main/12_%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
# 학습 데이터 셋
x_train = torch.FloatTensor([[1], [2], [3], [4]])
y_train = torch.FloatTensor([[50], [70], [90], [85]])

In [7]:
# y = W(Weight)x + b(bias)

'''
y = 20x + 15

시간      1     2     3     4
실제값    50    70    90    85
예측값    35    55    75    95
-------------------------------
오차값    15    15    15    -10
'''

# MSE(평균 제곱 오차: Mean squared error)
# 오차를 제곱하고 평균으로 나눈 것

# 코드를 재실행해도 같은 랜덤 결과가 나옴
torch.manual_seed(10)

print(x_train)
print(x_train.shape)

print(y_train)
print(y_train.shape)

# 선형회귀의 핵심은 학습데이터와 가장 잘 맞는 직선을 찾는 작업
# requires_grad=True: 학습을 통해 변경되는 변수
# y = 0*x + 0
W = torch.zeros(1, requires_grad=True)
print(W)

b = torch.zeros(1, requires_grad=True)
print(b)

H = x_train * W + b

tensor([[1.],
        [2.],
        [3.],
        [4.]])
torch.Size([4, 1])
tensor([[50.],
        [70.],
        [90.],
        [85.]])
torch.Size([4, 1])
tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [8]:
# 비용 함수 선언(cost function), 손실 함수(loss function), 오차 함수(error function)
cost = torch.mean((H - y_train) ** 2)
print(cost)

tensor(5681.2500, grad_fn=<MeanBackward0>)


In [9]:
# 옵티마이저(optimizer)
# 비용함수의 값을 최소로 하는 W(기울기)와 b(절편)을 찾는 방법(알고리즘)

# 경사하강법(Gradient Descent)
# 가장 기본적인 옵티마이저 알고리즘
# cost가 최소화 되는 지점은 접선의 기울기가 0이 되는 지점이며 미분값이 0이 되는 지점
# 비용함수를 미분하여 현재 W에서의 접선의 기울기를 구하고 접선의 기울기가 낮은 방향으로 W의 값을 업데이트 하는 작업을 반복

# SGD(Stochastic Gradient Descent)
# 배치 크기가 1인 경사하강법 알고리즘
# 확률적 경사하강법은 데이터 셋에서 무작위로 균일하게 선택한 하나의 예를 의존하여 각 단계의 예측 경사를 계산

# 학습률(learning rate)
# 기울기의 값을 변경할 때 얼마나 크게 변경할지를 결정
optimizer = optim.SGD([W, b], lr=0.01)

In [10]:
# gradient를 0으로 초기화
optimizer.zero_grad()
# 비용함수를 미분하여 gradient 계산
cost.backward()
# W와 b를 업데이트
optimizer.step()

In [ ]:
# 에폭(epoch): 전체 훈련 데이터가 학습에 한번 사용된 주기
# 총 에폭을 2000번, 100번 마다 로그 출력

