<a href="https://colab.research.google.com/github/jeungsengho/python8month/blob/main/5_%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C%EC%9A%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 텐서플로우(TensorFlow)

* 텐서플로우는 ML모델을 개발하고 학습시키는데 도움이 되는 핵심 오픈 소스 라이브러리
* 텐서플로우 2.x에서는 케라스를 딥러닝 공식 API로 채택하였고, 텐서플로우 내의 하나의 프레임워크로 개발되고 있음

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.8.2


### 1-1. Tensor
* Tensor는 multi-dimensional array를 나타내는 말
* Tensorflow의 기본 data type

In [4]:
hello = tf.constant([3, 3], dtype=tf.float32)
print(hello)

hello = tf.constant('Hello Tensor!!')
print(hello)

tf.Tensor([3. 3.], shape=(2,), dtype=float32)
tf.Tensor(b'Hello Tensor!!', shape=(), dtype=string)


In [8]:
x = tf.constant([[1.0, 2.0], [3.0, 4.0]])
print(x)
print(type(x))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [9]:
import numpy as np

In [10]:
x_np = np.array([[1.0, 2.0],
                [3.0, 4.0]])
x_list = [[1.0, 2.0],
          [3.0, 4.0]]

print(type(x_np))
print(type(x_list))

<class 'numpy.ndarray'>
<class 'list'>


In [13]:
# ndarray를 tensor로 변환
x_np_tf = tf.convert_to_tensor(x_np)
# list를 tensor로 변환
x_list_tf = tf.convert_to_tensor(x_list)

print(type(x_np_tf))
print(type(x_list_tf))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [15]:
# tensor를 numpy의 ndarray로 변환
x_np_tf.numpy()
print(type(x_np_tf.numpy()))

<class 'numpy.ndarray'>


### 1-2. 텐서플로우 함수

In [18]:
a = tf.ones((2, 3))
print(a)


b = tf.zeros((2, 3))
print(b)

c = tf.fill((2, 3), 2)
print(c)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2 2 2]
 [2 2 2]], shape=(2, 3), dtype=int32)


In [20]:
d = tf.zeros_like(c) # shape와 dtype만 복사 (데이터는 복사하지 않음)
print(d)

e = tf.ones_like(c)
print(e)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [21]:
g = tf.range(10)
print(g)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [23]:
h = tf.random.uniform((2, 2)) # uniform(): 2개의 숫자 사이의 랜덤 실수를 리턴
print(h)

i = tf.random.normal((2, 2))
print(i)

tf.Tensor(
[[0.33251214 0.7787603 ]
 [0.87954545 0.40324676]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.32132205 -0.5703143 ]
 [ 1.4022222   0.36910802]], shape=(2, 2), dtype=float32)


### 1-3. Tensor의 속성

In [24]:
tensor = tf.random.normal((3, 4))
print(f'Shape: {tensor.shape}')
print(f'DataType: {tensor.dtype}')

Shape: (3, 4)
DataType: <dtype: 'float32'>


In [26]:
tensor = tf.reshape(tensor, (4, 3))
tensor = tf.cast(tensor, tf.int32)
print(f'Shape: {tensor.shape}')
print(f'DataType: {tensor.dtype}')

Shape: (4, 3)
DataType: <dtype: 'int32'>


### 1-4. Variable
* Variable은 변할 수 있는 상태를 저장하는데 사용되는 특별한 텐서
* 딥러닝에서는 학습해야 하는 가중치(weight, bias)들을 Variable로 생성

In [30]:
tensor = tf.ones((3, 4))
print(tensor)

tensor[0, 0] = 100 # TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


TypeError: ignored

In [35]:
# assign() : 값 설정
# assign_add() : 값 더하기
# assign_sub() : 값 빼기

var = tf.Variable(tensor)
print(var)

var[0, 0].assign(100)
print(var)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[100.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]], dtype=float32)>


In [41]:
value1 = tf.random.normal(shape=(2, 2))
value1 = tf.Variable(value1)
print(value1)
value2 = tf.random.normal(shape=(2, 2))
print(value2)
value1.assign(value2)
print(value1)

value3 = tf.ones(shape=(2, 2))
value1.assign_add(value3)
print(value1)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.3423449, -0.6557697],
       [-1.3845158, -1.2702179]], dtype=float32)>
tf.Tensor(
[[-2.031311  -0.9434873]
 [ 0.2687878 -1.2055938]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.031311 , -0.9434873],
       [ 0.2687878, -1.2055938]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-1.031311  ,  0.05651271],
       [ 1.2687879 , -0.20559382]], dtype=float32)>


### 1-5. indexing과 slicing

In [44]:
a = tf.range(1, 13)
print(a)

a = tf.reshape(a, (3, 4))
print(a)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)


In [46]:
# indexing을 하면 차원이 감소하게 됨
print(a[1])
print(a[0, -1])

tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [48]:
# slicing을 하면 차원이 유지됨
print(a[1:-1])
print(a[:2, 2:])

tf.Tensor([[5 6 7 8]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[3 4]
 [7 8]], shape=(2, 2), dtype=int32)


### 1-6. 차원 바꾸기

In [49]:
a = tf.range(16)
print(a)
a = tf.reshape(a, (2, 2, -1)) # -1 자동으로 만들으라는 뜻
print(a)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15], shape=(16,), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]], shape=(2, 2, 4), dtype=int32)


In [50]:
# transpose: 행렬의 차원을 인덱스로 변환 -> [0]차원 [1]행 [2]열
b = tf.transpose(a, (2, 0, 1))  
# 2차원 2행 4열 -> 4차원 2행 2열로 변환
print(b)

tf.Tensor(
[[[ 0  4]
  [ 8 12]]

 [[ 1  5]
  [ 9 13]]

 [[ 2  6]
  [10 14]]

 [[ 3  7]
  [11 15]]], shape=(4, 2, 2), dtype=int32)


### 1-7. Tensor 연산

In [51]:
x = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
y = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)
print(x)
print(y)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


In [56]:
print(tf.add(x, y))
print(tf.subtract(x, y))
print(tf.multiply(x, y))
print(tf.matmul(x, y))

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [57]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x @ y)

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [58]:
z = tf.range(1, 11)
print(z)
z = tf.reshape(z, (2, 5))
print(z)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)


In [60]:
# reduce_sum(): 요소의 합계를 구함
print(tf.reduce_sum(z))

tf.Tensor(55, shape=(), dtype=int32)


In [61]:
sum1 = tf.reduce_sum(z, axis=0) # 행 연산
print(sum1)

tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)


In [62]:
sum2 = tf.reduce_sum(z, axis=1) # 열 연산
print(sum2)

tf.Tensor([15 40], shape=(2,), dtype=int32)


In [64]:
sum3 = tf.reduce_sum(z, axis=-1) # 열, 항상 차원의 마지막 방향 연산
print(sum3)

tf.Tensor([15 40], shape=(2,), dtype=int32)


In [65]:
concat = tf.concat([z, z], axis=0)
print(concat)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(4, 5), dtype=int32)


In [66]:
# concat() : 행과 열을 합침
concat = tf.concat([z, z], axis=1)
print(concat)

tf.Tensor(
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]], shape=(2, 10), dtype=int32)


In [67]:
concat = tf.concat([z, z], axis=-1)
print(concat)

tf.Tensor(
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]], shape=(2, 10), dtype=int32)
