<a href="https://colab.research.google.com/github/jeungsengho/python8month/blob/main/6_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 파이토치(Pytorch)

* Pytorch는 tensorflow와 함께 머신러닝, 딥러닝에서 가장 널리 사용되는 framework
* framework : 이미 틀은 만들어져 있고 그 안을 채워가며 개발하는 것
* 초기에는 Torch라는 이름으로 Lua언어 기반으로 만들어졌으나, 이후 Python 기반으로 변경한 것이 Pytorch
* NewYork 대학교와 FaceBook이 공동으로 개발하였고, 현재 가장 대중적이고 널리 사용되는 framework

In [2]:
import torch
print(torch.__version__)

1.12.1+cu113


### 1-1. Tensor
* 텐서는 배열이나 행렬과 매우 유사한 특수 자료구조
* 파이토치는 텐서를 사용하여 모델의 입력과 출력, 모델의 매개변수들을 부호화함

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [4]:
import numpy as np

In [5]:
np_array = np.array(data)
x_np_1 = torch.tensor(np_array)
print(x_np_1)

tensor([[1, 2],
        [3, 4]])


In [6]:
x_np_1[0, 0] = 100
print(x_np_1) # 새로운 텐서
print(np_array) # 기존 ndarray

tensor([[100,   2],
        [  3,   4]])
[[1 2]
 [3 4]]


In [7]:
x_np_2 = torch.as_tensor(np_array)  # 동일한 메모리 주소를 가리키는 뷰를 만듬
print(x_np_2)

tensor([[1, 2],
        [3, 4]])


In [8]:
x_np_2[0, 0] = 200
print(x_np_2)
print(np_array)

tensor([[200,   2],
        [  3,   4]])
[[200   2]
 [  3   4]]


In [9]:
x_np_3 = torch.from_numpy(np_array) # 동일한 메모리 주소를 가리키는 뷰를 만듬
print(x_np_3)

tensor([[200,   2],
        [  3,   4]])


In [10]:
x_np_3[0, 0] = 300
print(x_np_3)
print(np_array)

tensor([[300,   2],
        [  3,   4]])
[[300   2]
 [  3   4]]


In [11]:
np_again = x_np_1.numpy()
print(np_again, type(np_again))

[[100   2]
 [  3   4]] <class 'numpy.ndarray'>


In [12]:
a = torch.ones(2, 3)
print(a)

b = torch.zeros(2, 3)
print(b)

c = torch.full((2, 3), 2)
print(c)

d = torch.empty(2, 3)
print(d)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[2, 2, 2],
        [2, 2, 2]])
tensor([[1.0230e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 1.0000e+00]])


In [13]:
e = torch.eye(3)
print(e)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [14]:
f = torch.arange(10)
print(f)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [15]:
g = torch.rand(2, 2)
print(g)

h = torch.randn(2, 2)
print(h)

tensor([[0.5506, 0.1356],
        [0.4304, 0.4874]])
tensor([[-0.5642, -2.3217],
        [-0.4280, -0.1441]])


### 1-2. Tensor 속성

In [16]:
tensor = torch.rand(3, 4)
print(f'shape: {tensor.shape}')
print(f'type: {tensor.dtype}')
print(f'device: {tensor.device}')

shape: torch.Size([3, 4])
type: torch.float32
device: cpu


In [17]:
# 속성 변경 
# 코랩에서 device 변경하는 방법 : 런타임 -> 런타임 유형 변경 -> 하드웨어 가속기를 gpu로 변경
tensor = tensor.reshape(4, 3) # 안에 있는 요소의 갯수만 맞춰주면 바꿀 수 있다.
tensor = tensor.int()
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

print(f'shape: {tensor.shape}')
print(f'type: {tensor.dtype}')
print(f'device: {tensor.device}')

shape: torch.Size([4, 3])
type: torch.int32
device: cuda:0


### 1-3. Indexing과 Slicing

In [18]:
a = torch.arange(1, 13).reshape(3, 4)
print(a)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [22]:
print(a[1])
print(a[0, -1])
print(a[1:-1])
print(a[:2, 2:])

tensor([5, 6, 7, 8])
tensor(4)
tensor([[5, 6, 7, 8]])
tensor([[3, 4],
        [7, 8]])


### 1-4. Transpose (형태 변경)



In [23]:
a = torch.arange(16).reshape(2, 2, 4)
print(a, a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]]) torch.Size([2, 2, 4])


In [24]:
b = a.transpose(1, 2)
print(b, b.shape)

tensor([[[ 0,  4],
         [ 1,  5],
         [ 2,  6],
         [ 3,  7]],

        [[ 8, 12],
         [ 9, 13],
         [10, 14],
         [11, 15]]]) torch.Size([2, 4, 2])


In [25]:
c = a.permute((2, 0, 1))
print(c, c.shape)

tensor([[[ 0,  4],
         [ 8, 12]],

        [[ 1,  5],
         [ 9, 13]],

        [[ 2,  6],
         [10, 14]],

        [[ 3,  7],
         [11, 15]]]) torch.Size([4, 2, 2])


### 1-5. Tensor 연산

In [28]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [30]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x @ y)
print('*' * 30)
print(torch.add(x, y))
print(torch.subtract(x, y))
print(torch.multiply(x, y))
print(torch.divide(x, y))
print(torch.matmul(x, y))

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])
******************************
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])


In [33]:
# in-place 연산
print(x.add(y))
print(x)

print(x.add_(y)) # x에 결과를 다시 저장
print(x)

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[ 6.,  8.],
        [10., 12.]])


In [34]:
z = torch.arange(1, 11).reshape(2, 5)
print(z)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


In [39]:
sum1 = torch.sum(z, axis=0)
print(sum1, sum1.shape)

sum2 = torch.sum(z, axis=1)
print(sum2, sum2.shape)

sum3 = torch.sum(z, axis=-1)
print(sum3, sum3.shape)

tensor([ 7,  9, 11, 13, 15]) torch.Size([5])
tensor([15, 40]) torch.Size([2])
tensor([15, 40]) torch.Size([2])


In [40]:
a = torch.arange(24).reshape(4, 6)
b = a.clone().detach()
print(a, a.shape)
print(b, b.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])
